version: "3.8"

services:
  client:
    image: gdfa95713/thread-client:latest
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "80:80"

  server:
    image: gdfa95713/thread-server:latest
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongo:27017/threadDB
      NODE_ENV: production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
